export const API_REGISTER_NOTIFICATON: string = '/v1/subscribe'
export const API_GET_INFO_GENERAL: string = '/v1/get-info-general'
export const API_GET_INDIVIDUAL_CONTRACT: string = '/v1/get-individual-contract'
export const API_GET_INSURANCE_BY_ADDRESS: string = '/v1/get-insurance-by-address'
export const API_GET_GET_LIST_TOKEN: string = '/v1/admin/get-list-token'
